"""Add multimedia fields

Revision ID: 1ca7543b1f2b
Revises: a28596a92e55
Create Date: 2025-12-23 21:34:11.803667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca7543b1f2b'
down_revision = 'a28596a92e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('audio_url')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
