"""Add google_id to User model

Revision ID: 7c3702ecaf68
Revises: f26b7fab310b
Create Date: 2025-12-24 00:11:57.226489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3702ecaf68'
down_revision = 'f26b7fab310b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
