"""Add SiteSettings

Revision ID: f26b7fab310b
Revises: 1ca7543b1f2b
Create Date: 2025-12-23 22:28:31.961857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26b7fab310b'
down_revision = '1ca7543b1f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('github', sa.String(length=200), nullable=True),
    sa.Column('twitter', sa.String(length=200), nullable=True),
    sa.Column('youtube', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
